package View;

import Controller.DisponivelController;
import Model.Disponivel;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class PrincipalUsuario extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalUsuario
     */
    public PrincipalUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fundo = new javax.swing.JPanel();
        jPanelfundo3 = new javax.swing.JPanel();
        jToggleButtonLogo1 = new javax.swing.JToggleButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelExcluir1 = new javax.swing.JLabel();
        jLabelBemVindo1 = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jLabelNomeUsuario = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jLabelDisponibilidade = new javax.swing.JLabel();
        jScrollPaneInformacoes = new javax.swing.JScrollPane();
        jTextAreaBuscar = new javax.swing.JTextArea();
        jButtonLimpar = new javax.swing.JButton();
        jMenuBarMenu = new javax.swing.JMenuBar();
        jMenuSobre = new javax.swing.JMenu();
        jMenuAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(958, 677));

        Fundo.setBackground(new java.awt.Color(38, 185, 203));
        Fundo.setMinimumSize(new java.awt.Dimension(958, 627));

        jPanelfundo3.setBackground(new java.awt.Color(118, 206, 209));

        jToggleButtonLogo1.setBackground(new java.awt.Color(118, 206, 209));
        jToggleButtonLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/LOGO.png"))); // NOI18N

        jLabelExcluir1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelExcluir1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExcluir1.setText("Digite o nome do livro:");

        jLabelBemVindo1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelBemVindo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBemVindo1.setText("BEM-VINDO(A),");

        jTextFieldBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarActionPerformed(evt);
            }
        });

        jLabelNomeUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNomeUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelNomeUsuario.setForeground(new java.awt.Color(38, 185, 203));
        jLabelNomeUsuario.setText("USUÁRIO(A)");

        jButtonSair.setBackground(new java.awt.Color(28, 185, 203));
        jButtonSair.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonSair.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSair.setText("SAIR");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonBuscar.setBackground(new java.awt.Color(28, 185, 203));
        jButtonBuscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscar.setText("BUSCAR");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelfundo3Layout = new javax.swing.GroupLayout(jPanelfundo3);
        jPanelfundo3.setLayout(jPanelfundo3Layout);
        jPanelfundo3Layout.setHorizontalGroup(
            jPanelfundo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelfundo3Layout.createSequentialGroup()
                .addGroup(jPanelfundo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelfundo3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabelBemVindo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNomeUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelfundo3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
            .addGroup(jPanelfundo3Layout.createSequentialGroup()
                .addGroup(jPanelfundo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelfundo3Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jToggleButtonLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelfundo3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanelfundo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelExcluir1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelfundo3Layout.setVerticalGroup(
            jPanelfundo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelfundo3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jToggleButtonLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanelfundo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBemVindo1)
                    .addComponent(jLabelNomeUsuario)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                .addComponent(jLabelExcluir1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jLabelDisponibilidade.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelDisponibilidade.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDisponibilidade.setText("INFORMAÇÕES E DISPONIBILIDADE:");

        jTextAreaBuscar.setColumns(20);
        jTextAreaBuscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextAreaBuscar.setRows(5);
        jScrollPaneInformacoes.setViewportView(jTextAreaBuscar);

        jButtonLimpar.setBackground(new java.awt.Color(118, 206, 209));
        jButtonLimpar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonLimpar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLimpar.setText("LIMPAR DADOS");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FundoLayout = new javax.swing.GroupLayout(Fundo);
        Fundo.setLayout(FundoLayout);
        FundoLayout.setHorizontalGroup(
            FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FundoLayout.createSequentialGroup()
                .addGroup(FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonLimpar)
                    .addGroup(FundoLayout.createSequentialGroup()
                        .addComponent(jPanelfundo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDisponibilidade)
                            .addComponent(jScrollPaneInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        FundoLayout.setVerticalGroup(
            FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelfundo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FundoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabelDisponibilidade)
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuSobre.setText("Sobre");
        jMenuSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSobreMouseClicked(evt);
            }
        });
        jMenuBarMenu.add(jMenuSobre);

        jMenuAjuda.setText("Ajuda");
        jMenuAjuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAjudaMouseClicked(evt);
            }
        });
        jMenuBarMenu.add(jMenuAjuda);

        setJMenuBar(jMenuBarMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAjudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAjudaMouseClicked
        Ajuda ajuda = new Ajuda();
        ajuda.setVisible(true);
    }//GEN-LAST:event_jMenuAjudaMouseClicked

    private void jMenuSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSobreMouseClicked
        Sobre sobre = new Sobre();
        sobre.setVisible(true);
    }//GEN-LAST:event_jMenuSobreMouseClicked

    private void jTextFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "Você realmente deseja sair?", "Confirmar Saída", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (option == JOptionPane.YES_OPTION) {
            System.out.println("Usuário escolheu sair.");
            this.setVisible(false);
            Login login = new Login();
            login.setVisible(true);
        } else {
            System.out.println("Usuário escolheu não sair.");
        }
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        DisponivelController disponivel = new DisponivelController();
        try {
            Disponivel d = new Disponivel();
            d = disponivel.buscarLivro(jTextFieldBuscar.getText().toUpperCase());
            if (d != null) {
                jTextAreaBuscar.setText(d.toString());
                jTextFieldBuscar.setText("");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Nenhum livro encontrado", "ERRO AO BUSCAR LIVRO", 1);
                jTextAreaBuscar.setText("");
                jTextFieldBuscar.setText("");
            }
        } catch (IOException ex) {
            Logger.getLogger(PrincipalAdm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PrincipalAdm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        jTextAreaBuscar.setText("");
    }//GEN-LAST:event_jButtonLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalUsuario().setVisible(true);
            }
        });
    }

    public JLabel getjLabelNomeUsuario() {
        return jLabelNomeUsuario;
    }

    public void setjLabelNomeUsuario(JLabel jLabelNomeUsuario) {
        this.jLabelNomeUsuario = jLabelNomeUsuario;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fundo;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelBemVindo1;
    private javax.swing.JLabel jLabelDisponibilidade;
    private javax.swing.JLabel jLabelExcluir1;
    private javax.swing.JLabel jLabelNomeUsuario;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenuBar jMenuBarMenu;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JPanel jPanelfundo3;
    private javax.swing.JScrollPane jScrollPaneInformacoes;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextAreaBuscar;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JToggleButton jToggleButtonLogo1;
    // End of variables declaration//GEN-END:variables
}
