package View;

/**
 *
 * @author diego
 */
public class Sobre extends javax.swing.JFrame {

    /**
     * Creates new form Sobre
     */
    public Sobre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelTexto2 = new javax.swing.JLabel();
        jLabelTexto1 = new javax.swing.JLabel();
        jLabelTexto4 = new javax.swing.JLabel();
        jLabelTexto5 = new javax.swing.JLabel();
        jLabelTexto6 = new javax.swing.JLabel();
        jLabelTexto7 = new javax.swing.JLabel();
        jLabelTexto8 = new javax.swing.JLabel();
        jLabelTexto9 = new javax.swing.JLabel();
        jLabelTexto10 = new javax.swing.JLabel();
        jLabelTexto11 = new javax.swing.JLabel();
        jLabelTexto12 = new javax.swing.JLabel();
        jLabelTexto13 = new javax.swing.JLabel();
        jLabelTexto14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(38, 185, 203));

        jPanel2.setBackground(new java.awt.Color(118, 206, 209));

        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("INFORMAÇÕES SOBRE O SISTEMA:");

        jLabelTexto2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelTexto2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTexto2.setText("VERSÃO INICIAL: 1.0.0.");

        jLabelTexto1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelTexto1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTexto1.setText("NOME: BLIBIOTECH.");

        jLabelTexto4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelTexto4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTexto4.setText("DESENVOLVEDORES: ANA, DIEGO, JOÃO E PAOLA.");

        jLabelTexto5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelTexto5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTexto5.setText("DESCRIÇÃO: O SOFTWARE EM QUESTÃO É UMA SOLUÇÃO");

        jLabelTexto6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelTexto6.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTexto6.setText("SIMPLIFICADA PARA A GESTÃO DE UMA BIBLIOTECA, PRO- ");

        jLabelTexto7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelTexto7.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTexto7.setText("JETADA PARA AJUDAR NOS PROCESSOS ROTIEIROS DOS");

        jLabelTexto8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelTexto8.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTexto8.setText("ACERVOS INCLUIDOS NAS UNIVERSIDADES.");

        jLabelTexto9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelTexto9.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTexto9.setText("TERMOS DE USO E POLITICA DE PRIVACIDADE: (...)");

        jLabelTexto10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelTexto10.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTexto10.setText("CONTATO PARA SUPORTE: (00) 0 0000-0000");

        jLabelTexto11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelTexto11.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTexto11.setText("DIREITOS AUTORAIS: (...)");

        jLabelTexto12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelTexto12.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTexto12.setText("LICENÇA: (...)");

        jLabelTexto13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelTexto13.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTexto13.setText("REFERÊNCIAS E CREDITOS: (...)");

        jLabelTexto14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelTexto14.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTexto14.setText("HISTÓRICO DE VERSÕES: (...)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTexto4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTexto2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTexto14)
                            .addComponent(jLabelTexto13)
                            .addComponent(jLabelTexto12)
                            .addComponent(jLabelTexto11)
                            .addComponent(jLabelTexto10)
                            .addComponent(jLabelTexto9)
                            .addComponent(jLabelTexto8)
                            .addComponent(jLabelTexto7)
                            .addComponent(jLabelTexto6)
                            .addComponent(jLabelTexto5))
                        .addGap(0, 33, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabelTitulo)
                .addGap(35, 35, 35)
                .addComponent(jLabelTexto1)
                .addGap(18, 18, 18)
                .addComponent(jLabelTexto2)
                .addGap(18, 18, 18)
                .addComponent(jLabelTexto4)
                .addGap(18, 18, 18)
                .addComponent(jLabelTexto5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTexto6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTexto7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTexto8)
                .addGap(18, 18, 18)
                .addComponent(jLabelTexto9)
                .addGap(18, 18, 18)
                .addComponent(jLabelTexto10)
                .addGap(18, 18, 18)
                .addComponent(jLabelTexto11)
                .addGap(18, 18, 18)
                .addComponent(jLabelTexto12)
                .addGap(18, 18, 18)
                .addComponent(jLabelTexto13)
                .addGap(18, 18, 18)
                .addComponent(jLabelTexto14)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sobre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTexto1;
    private javax.swing.JLabel jLabelTexto10;
    private javax.swing.JLabel jLabelTexto11;
    private javax.swing.JLabel jLabelTexto12;
    private javax.swing.JLabel jLabelTexto13;
    private javax.swing.JLabel jLabelTexto14;
    private javax.swing.JLabel jLabelTexto2;
    private javax.swing.JLabel jLabelTexto4;
    private javax.swing.JLabel jLabelTexto5;
    private javax.swing.JLabel jLabelTexto6;
    private javax.swing.JLabel jLabelTexto7;
    private javax.swing.JLabel jLabelTexto8;
    private javax.swing.JLabel jLabelTexto9;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
